# This is a basic workflow to help you get started with Actions

name: Deploy CII

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch!
  push:
    branches: [docs]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-push')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Push to VPS
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /home/information && git reset --hard && git pull
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privatekey: ${{ secrets.PRIVATEKEY }}